Update source.rb
if hash is nil at this point, running the regex will produce:

`(irb):2:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError) `

it also doesn't seem to be necessary to do this here, since the next line calls `format_hash` if hash isn't nil.

format_hash will still run the regex if required.